export interface ThemeColors {
  activityIndicator: string;
  title: string;
  titleShadow: string;
  text: string;
  progressBar: string;
  screenBackground: string;
  horizontalPlayerBackground: string;
  horizontalPlayerShadow: string;
  horizontalPlayerBorderTop: string;
  trackCardBackground: string;
  trackCardShadow: string;
  trackHorizontalCardBackground: string;
  trackHorizontalCardShadow: string;
  playlistCardBackground: string;
  playlistCardShadow: string;
  playlistHorizontalCardBackground: string;
  playlistHorizontalCardShadow: string;
  artistCardBackground: string;
  artistCardShadow: string;
  artistCardHorizontalBackground: string;
  artistCardHorizontalShadow: string;
  configurationCardBackground: string;
  configurationCardShadow: string;
  inputTextColor: string;
  inputTextPlaceholderColor: string;
  inputTextBackground: string;
  drawerNavigationBackground: string;
  drawerNavigationActiveText: string;
  drawerNavigationInactiveText: string;
  bottomNavigationBackground: string;
  bottomNavigationActiveText: string;
  bottomNavigationInactiveText: string;
  playerModalContainerBackground: string;
  playerModalBackground: string;
  playerModalCloseButton: string;
}

export const lightTheme: ThemeColors = {
  activityIndicator: "blue",
  title: "black",
  titleShadow: "lightgray",
  text: "black",
  progressBar: "blue",
  screenBackground: "#fff",
  horizontalPlayerBackground: "#f8f8f8",
  horizontalPlayerShadow: "#000",
  horizontalPlayerBorderTop: "#e3e3e3",
  trackCardBackground: "#f8f8f8",
  trackCardShadow: "#000",
  trackHorizontalCardBackground: "#f8f8f8",
  trackHorizontalCardShadow: "#000",
  playlistCardBackground: "#f8f8f8",
  playlistCardShadow: "#000",
  playlistHorizontalCardBackground: "#f8f8f8",
  playlistHorizontalCardShadow: "#000",
  artistCardBackground: "#f8f8f8",
  artistCardShadow: "#000",
  artistCardHorizontalBackground: "#f8f8f8",
  artistCardHorizontalShadow: "#000",
  configurationCardBackground: "#f8f8f8",
  configurationCardShadow: "#000",
  inputTextColor: "black",
  inputTextPlaceholderColor: "gray",
  inputTextBackground: "white",
  drawerNavigationBackground: "#fff",
  drawerNavigationActiveText: "black",
  drawerNavigationInactiveText: "gray",
  bottomNavigationBackground: "#f8f8f8",
  bottomNavigationActiveText: "black",
  bottomNavigationInactiveText: "gray",
  playerModalContainerBackground: "rgba(0, 0, 0, 0.5)",
  playerModalBackground: "#fff",
  playerModalCloseButton: "black",
};

export const darkTheme: ThemeColors = {
  activityIndicator: "orange",
  title: "white",
  titleShadow: "darkgray",
  text: "white",
  progressBar: "orange",
  screenBackground: "#212121",
  horizontalPlayerBackground: "#212121",
  horizontalPlayerShadow: "#fff",
  horizontalPlayerBorderTop: "#1c1c1c",
  trackCardBackground: "#212121",
  trackCardShadow: "#fff",
  trackHorizontalCardBackground: "#212121",
  trackHorizontalCardShadow: "#fff",
  playlistCardBackground: "#212121",
  playlistCardShadow: "#fff",
  playlistHorizontalCardBackground: "#212121",
  playlistHorizontalCardShadow: "#fff",
  artistCardBackground: "#212121",
  artistCardShadow: "#fff",
  artistCardHorizontalBackground: "#212121",
  artistCardHorizontalShadow: "#fff",
  configurationCardBackground: "#333333",
  configurationCardShadow: "#fff",
  inputTextColor: "white",
  inputTextPlaceholderColor: "lightgray",
  inputTextBackground: "#212121",
  drawerNavigationBackground: "#212121",
  drawerNavigationActiveText: "white",
  drawerNavigationInactiveText: "gray",
  bottomNavigationBackground: "#212121",
  bottomNavigationActiveText: "white",
  bottomNavigationInactiveText: "gray",
  playerModalContainerBackground: "rgba(0, 0, 0, 0.5)",
  playerModalBackground: "#111111",
  playerModalCloseButton: "gray",
};
